AWSTemplateFormatVersion: "2010-09-09"
Discription:
  Create a basic template that will setup three resources

Resources:
  WebserverSecurityGroup:
  Type: AWS::EC2::SecurityGroup
  Properties:
      GroupDescription: Enable HTTP access via port 80 + SSH access
      #VpcId:
       #  Ref: myVPC
#Here I am allowing two rules for my in comming and out going trafic
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
# My EC2
  WebServer:
    Type: AWS::EC2::Instance
    Properties: 
      # 4 properties of my server 
      ImageId: ami-01419b804382064e4
      InstanceType: t2.small
      SecurityGroups: !Ref WebServerSecurityGroup
      #Use KeyName for SSH
      KeyName: sanaU.CloudFormation
    
      Metadata:
        Instance:
          Description: This server hosts my blog

#Create resource number four: Elastic IP address
  IPAddress:
    Type: AWS::EC2::EIP
    # Now associate it to an EC2 resource
  IPAssoc:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref WebServer
      EIP: !Ref IPAddress